### ISSUE TITLE
4. 서버에서 클라이언트 접속을 받을 것

### ISSUE THREAD

**Issue by zrma** [zrma/DailyCoding#4]
- 임의의 포트 번호를 정해서 bind
- listen을 시작하고
- accept를 통해서 클라이언트 접속을 받아, 접속에 고유 번호를 부여하여 적절한 자료구조에 저장할 것

https://github.com/zeliard/EasyGameServer
필요하다면 이 곳의 소스코드들을 참고로하고,

https://github.com/zrma/EasyGameServer
이곳처럼 자신이 모르는 부분은 주석 처리를 해 가면서 공부할 것.

**Comment by LeeInJae** [comment]
server 만들었으나 accept가 되지 않음

**Comment by zrma** [comment]
01baef35df4534f8543969aafbd1e00471d88133
